application: chatter-now
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:  
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
  
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /sounds
  static_dir: sounds
  
- url: /scripts
  static_dir: scripts

- url: /.*
  script: chatter.app

libraries:
- name: jinja2
  version: latest
  
- name: django
  version: "1.2"